### ISSUE TITLE
Create binary that can be deployed in a cluster

### ISSUE THREAD

**Issue by aojea** [mneverov/cluster-cidr-controller#1]
This looks good, but we also need to provide users with the capability to use it independently, take per example a look at this project of mine https://github.com/aojea/kindnet

It has a Dockerfile and provides a manifests to install it.

It also has a github action to run e2e tests https://github.com/aojea/kindnet/tree/master/.github/workflows 

Great work, we are close

**Comment by mneverov** [comment]
Dockerfile exists. Created two separate tasks: [add helm charts](https://github.com/mneverov/cluster-cidr-controller/issues/13) and [add e2e tests](https://github.com/mneverov/cluster-cidr-controller/issues/11)
