### ISSUE TITLE
Provide CRDs

### ISSUE THREAD

**Issue by aojea** [mneverov/cluster-cidr-controller#2]
The golang types exist, but users need to be able to deploy them as a CRD, commonly people use https://github.com/kubernetes-sigs/kubebuilder for these things

**Comment by mneverov** [comment]
Addressed in #7 , ptal [CRD](https://github.com/mneverov/cluster-cidr-controller/blob/main/config/crd/networking.x-k8s.io_clustercidrs.yaml)
